spring:
   datasource:
     username: coffee_store
     password: coffee_store
     url: jdbc:mysql://localhost:3306/coffee_store
     
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
     